# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Provider')),
            ],
        ),
    ]
