# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='raw_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
